#!/bin/bash
cd /usr/share/swingsane
chmod +x /usr/share/swingsane/swingsane.sh
tar zxvf /usr/share/swingsane/jre-8u31-linux-x64.tar.gz
ln -s /usr/share/swingsane/jre1.8.0_31 /usr/share/swingsane/jre
rm /usr/share/swingsane/jre-8u31-linux-x64.tar.gz
