#!/bin/bash
cd /usr/share/swingsane
chmod +x /usr/share/swingsane/swingsane.sh

# if need to include a jre in future...
# tar zxvf /usr/share/swingsane/jre.tar.gz
# chown -R root:root /usr/share/swingsane/jre1.8.0_31
# ln -s /usr/share/swingsane/jre1.8.0_31 /usr/share/swingsane/jre
# rm /usr/share/swingsane/jre.tar.gz
